name: GitHub Actions Demo
on: 
  push:
    branches: main
    paths-ignore: .github/**
  pull_request:
    branches: main
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "The job was triggered by event: ${{ github.event_name }}"
          echo "The name of your branch is ${{ github.ref }} and your repository is ."
          echo "Dump Github actions: ${{ toJSON(matrix) }}"
      - uses: actions/checkout@v4.2.2
      - name: List all files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree

      - name: Run my own container action
        id: hello-action
        uses: .
        with:
          who-to-greet: '@Patricio'

      - name: Output time set in the container
        run: echo "The time was ${{ steps.hello-action.outputs.time }} when the action said hello"

  
  
